// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzkFHlHLbhJ3_6UMNInWh-WXBttqYHRno',
    appId: '1:879464723021:web:47c9e79910aa3de08c6204',
    messagingSenderId: '879464723021',
    projectId: 'bancodedados-dd5bd',
    authDomain: 'bancodedados-dd5bd.firebaseapp.com',
    databaseURL: 'https://bancodedados-dd5bd.firebaseio.com',
    storageBucket: 'bancodedados-dd5bd.appspot.com',
    measurementId: 'G-PZGNBCQBP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7JTIFotkdhBZfp4Jhv1UeaUabVrfCuLM',
    appId: '1:879464723021:android:8f0d29e5426d241e8c6204',
    messagingSenderId: '879464723021',
    projectId: 'bancodedados-dd5bd',
    databaseURL: 'https://bancodedados-dd5bd.firebaseio.com',
    storageBucket: 'bancodedados-dd5bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf1MXo-CBc4DqefD2_SkdzeVG8K3qKPuc',
    appId: '1:879464723021:ios:81866fa244578bc68c6204',
    messagingSenderId: '879464723021',
    projectId: 'bancodedados-dd5bd',
    databaseURL: 'https://bancodedados-dd5bd.firebaseio.com',
    storageBucket: 'bancodedados-dd5bd.appspot.com',
    iosClientId: '879464723021-5tmd0dcli2mritjn9a8r7rcl5gv3c5de.apps.googleusercontent.com',
    iosBundleId: 'com.example.comunicaBeacons',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf1MXo-CBc4DqefD2_SkdzeVG8K3qKPuc',
    appId: '1:879464723021:ios:81866fa244578bc68c6204',
    messagingSenderId: '879464723021',
    projectId: 'bancodedados-dd5bd',
    databaseURL: 'https://bancodedados-dd5bd.firebaseio.com',
    storageBucket: 'bancodedados-dd5bd.appspot.com',
    iosClientId: '879464723021-5tmd0dcli2mritjn9a8r7rcl5gv3c5de.apps.googleusercontent.com',
    iosBundleId: 'com.example.comunicaBeacons',
  );
}
